### ISSUE TITLE
Private resquest

### ISSUE THREAD

**Issue by royalterra** [hugsbrugs/php-phantomjs-get-html#2]
hi can you help me in a private project with your php phantomjs . We can negotiate any $$ for your job

**Comment by hugsbrugs** [comment]
Hi,

why not ! Explain me your project.

In fact I don't use this repository any more since phantomjs is a nodejs program that should be runned from a nodejs script. The PHP part is very simple : just call a nodejs script with some parameters if needed. If you have scenario (click a link, connect as a user ...) then casperjs is the way to go.

My prices are 40€/hour. I'm a french living independant programmer. I have never had clients abroad ! Where are you from ?

Hugo

**Comment by royalterra** [comment]
Hi I live in Britain but I am not English anyway I am company can be check . The question is I have a software is not very Search engine friendly I am looking how to make more easy. If you want more details we can talk better in private if you have a email

**Comment by hugsbrugs** [comment]
Hi sorry for the delay,
you can write to hugo at maugey.fr

**Comment by royalterra** [comment]
Hugo I am not interest in use nodejs for not depend of more software.
But possible you will like to look https://github.com/BlaBlaNet/BlaBlaNet I
need the Search engines find easy the users post with the title and
description .
If you make a search like blablanet usa in google you can find something
like
BlaBlanet-ES [blablanet-es@blablanet.es] BlaBlanet-ES
and here a description of last post

But Google and other search engines no Craw all the public post only the
first post with tittle the user name no the post in question
